CREATE TABLE INVOICES (
  ID INTEGER PRIMARY KEY,
  AMOUNT INTEGER NOT NULL,
  DATE date NOT NULL
);

CREATE TABLE INVOICES_ITEMS(
    ID INTEGER PRIMARY KEY,
    AMOUNT INTEGER,
    AUTO_TRANSFER INTEGER,
    DESCRIPTION VARCHAR(255)
);

INSERT INTO INVOICES VALUES (1,100,'2020-12-24');
INSERT INTO INVOICES VALUES (2,200,'2020-12-12');
INSERT INTO INVOICES VALUES (3,300,'2020-11-20');

INSERT INTO INVOICES_ITEMS VALUES (100,50,1,'carnes');
INSERT INTO INVOICES_ITEMS VALUES (101,25,1,'cereales');
INSERT INTO INVOICES_ITEMS VALUES (102,25,1,'sal');
INSERT INTO INVOICES_ITEMS VALUES (103,150,2,'bebidas');
INSERT INTO INVOICES_ITEMS VALUES (104,50,2,'carnes');
INSERT INTO INVOICES_ITEMS VALUES (105,10,3,'cereales');
INSERT INTO INVOICES_ITEMS VALUES (106,100,3,'carnes');
INSERT INTO INVOICES_ITEMS VALUES (107,100,3,'cafe');
INSERT INTO INVOICES_ITEMS VALUES (108,90,3,'frutas');

CREATE VIEW PRUEBASQL
AS
SELECT T1.ID , 
    SUM(CASE WHEN T2.DESCRIPTION = 'carnes' THEN T2.AMOUNT END) AS 'CARNES',
    SUM(CASE WHEN T2.DESCRIPTION = 'cereales' THEN T2.AMOUNT END) AS 'CEREALES',
    SUM(CASE WHEN T2.DESCRIPTION IN ('sal','bebidas','cafe','frutas') THEN T2.AMOUNT END) AS 'OTROS'
FROM INVOICES T1
JOIN INVOICES_ITEMS T2 on (T1.ID=T2.AUTO_TRANSFER)
GROUP BY T1.ID;
GO

SELECT * FROM PRUEBASQL